language: python

sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - "pip install --upgrade pip"
  # Actually install our dependencies now
  - pip install -r requirements.txt

script: true
